# Generated by Django 5.2.7 on 2025-10-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
